<a href="https://colab.research.google.com/github/priofallsyns/AI-ML-Learning-Experience/blob/main/IntroToPreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import pandas as pd

In [111]:
d = {
    "Sales": [100000, 222000, 150000, 180000, 120000, 200000, 250000, 175000, 140000, 230000,
              260000, 190000, 160000, 210000, 240000, 170000, 130000, 220000, 200000, 180000],
    "City": ["Tampa", "Orlando", "Miami", "Jacksonville", "Tampa", "Orlando", "Miami", "Jacksonville",
             "Tampa", "Orlando", "Miami", "Jacksonville", "Tampa", "Orlando", "Miami", "Jacksonville",
             "Tampa", "Orlando", "Miami", "Jacksonville"],
    "Size": ["Small", "Medium", "Large", "Medium", "Small", "Large", "Medium", "Small", "Medium", "Small",
             "Large", "Medium", "Large", "Medium", "Small", "Large", "Medium", "Large", "Medium", "Small"]
}


In [112]:
df=pd.DataFrame(data=d)

In [113]:
df.head()

Sales          City    Size
0  100000         Tampa   Small
1  222000       Orlando  Medium
2  150000         Miami   Large
3  180000  Jacksonville  Medium
4  120000         Tampa   Small

In [114]:
from sklearn.preprocessing import OneHotEncoder

In [115]:
ohe=OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')

In [116]:
ohetransformed=ohe.fit_transform(df[['City']])

In [117]:
ohetransformed.head()

City_Jacksonville  City_Miami  City_Orlando  City_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           1.0         0.0
2                0.0         1.0           0.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         0.0           0.0         1.0

In [118]:
df=pd.concat([df, ohetransformed], axis=1).drop(columns=['City'])

In [119]:
df.head()

Sales    Size  City_Jacksonville  City_Miami  City_Orlando  City_Tampa
0  100000   Small                0.0         0.0           0.0         1.0
1  222000  Medium                0.0         0.0           1.0         0.0
2  150000   Large                0.0         1.0           0.0         0.0
3  180000  Medium                1.0         0.0           0.0         0.0
4  120000   Small                0.0         0.0           0.0         1.0

In [120]:
from sklearn.preprocessing import OrdinalEncoder

In [121]:
sizes=df['Size'].unique()
print(sizes)

['Small' 'Medium' 'Large']


In [122]:
oe=OrdinalEncoder(categories=[sizes], handle_unknown='use_encoded_value', unknown_value=-1)

In [123]:
df['Size']=oe.fit_transform(df[['Size']])

In [124]:
df.head()

Sales  Size  City_Jacksonville  City_Miami  City_Orlando  City_Tampa
0  100000   0.0                0.0         0.0           0.0         1.0
1  222000   1.0                0.0         0.0           1.0         0.0
2  150000   2.0                0.0         1.0           0.0         0.0
3  180000   1.0                1.0         0.0           0.0         0.0
4  120000   0.0                0.0         0.0           0.0         1.0

In [125]:
#This marks a new data usage:

In [126]:
import numpy as np


In [127]:
miles=pd.DataFrame({"Farthest_run_mi":[50, 62, np.nan , 100, 26, 13, 50]})

In [128]:
miles

Farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             50.0

In [129]:
miles.isna().sum()

Farthest_run_mi    1
dtype: int64

In [130]:
from sklearn.impute import SimpleImputer

In [131]:
si_mean=SimpleImputer(strategy='mean')

In [132]:
si_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 50.16666667],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 50.        ]])

In [133]:
si_median=SimpleImputer(strategy='median')

In [134]:
si_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 50.]])

In [135]:
si_mode=SimpleImputer(strategy='most_frequent')

In [136]:
si_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 50.]])

In [137]:
si_con=SimpleImputer(strategy='constant', fill_value=13)

In [138]:
si_con.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 50.]])

In [139]:
names=pd.DataFrame({"names":["Messi", "abidou", "cristiano", "Abdelhak", "Pessi", np.nan, "HHHH", "spongebob", np.nan]})

In [140]:
names

names
0      Messi
1     abidou
2  cristiano
3   Abdelhak
4      Pessi
5        NaN
6       HHHH
7  spongebob
8        NaN

In [141]:
names.isna().sum()

names    2
dtype: int64

In [142]:
si_namefiller=SimpleImputer(strategy="constant", fill_value="Unnamed Artist")

In [143]:
si_namefiller.fit_transform(names)

array([['Messi'],
       ['abidou'],
       ['cristiano'],
       ['Abdelhak'],
       ['Pessi'],
       ['Unnamed Artist'],
       ['HHHH'],
       ['spongebob'],
       ['Unnamed Artist']], dtype=object)

In [144]:
df=pd.concat([miles, names], axis=1)

In [145]:
df

Farthest_run_mi      names
0             50.0      Messi
1             62.0     abidou
2              NaN  cristiano
3            100.0   Abdelhak
4             26.0      Pessi
5             13.0        NaN
6             50.0       HHHH
7              NaN  spongebob
8              NaN        NaN

In [146]:
gdf=pd.concat([pd.DataFrame(si_mean.fit_transform(miles), columns=["miles"]), pd.DataFrame(si_namefiller.fit_transform(names), columns=["names"])], axis=1)

In [147]:
gdf

miles           names
0   50.000000           Messi
1   62.000000          abidou
2   50.166667       cristiano
3  100.000000        Abdelhak
4   26.000000           Pessi
5   13.000000  Unnamed Artist
6   50.000000            HHHH
7         NaN       spongebob
8         NaN  Unnamed Artist

In [148]:
#Columns transfer simplified :

In [149]:
#we will use the first data 'd' we used in the start

In [150]:
df=pd.DataFrame(data=d)

In [151]:
df

Sales          City    Size
0   100000         Tampa   Small
1   222000       Orlando  Medium
2   150000         Miami   Large
3   180000  Jacksonville  Medium
4   120000         Tampa   Small
5   200000       Orlando   Large
6   250000         Miami  Medium
7   175000  Jacksonville   Small
8   140000         Tampa  Medium
9   230000       Orlando   Small
10  260000         Miami   Large
11  190000  Jacksonville  Medium
12  160000         Tampa   Large
13  210000       Orlando  Medium
14  240000         Miami   Small
15  170000  Jacksonville   Large
16  130000         Tampa  Medium
17  220000       Orlando   Large
18  200000         Miami  Medium
19  180000  Jacksonville   Small

In [152]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [153]:
ohe=OneHotEncoder(sparse_output=False) #to make sure we can get the output as pandas DF

In [154]:
ode=OrdinalEncoder()

In [155]:
from sklearn.compose import make_column_transformer

In [156]:
ct=make_column_transformer(
    (ohe, ['City']),
    (ode, ['Size']),
    remainder='passthrough'
)

In [157]:
ct.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['City']),
                                ('ordinalencoder', OrdinalEncoder(), ['Size'])])

In [158]:
df_workedon=ct.fit_transform(df)

In [159]:
df_workedon

onehotencoder__City_Jacksonville  onehotencoder__City_Miami  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        1.0   
3                                1.0                        0.0   
4                                0.0                        0.0   
5                                0.0                        0.0   
6                                0.0                        1.0   
7                                1.0                        0.0   
8                                0.0                        0.0   
9                                0.0                        0.0   
10                               0.0                        1.0   
11                               1.0                        0.0   
12                               0.0                        0.0   
13                               0.0                        0.0   
14                               0.0                        1.0   
15                               1.0                        0.0   
16                               0.0                        0.0   
17                               0.0                        0.0   
18                               0.0                        1.0   
19                               1.0                        0.0   

    onehotencoder__City_Orlando  onehotencoder__City_Tampa  \
0                           0.0                        1.0   
1                           1.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        1.0   
5                           1.0                        0.0   
6                           0.0                        0.0   
7                           0.0                        0.0   
8                           0.0                        1.0   
9                           1.0                        0.0   
10                          0.0                        0.0   
11                          0.0                        0.0   
12                          0.0                        1.0   
13                          1.0                        0.0   
14                          0.0                        0.0   
15                          0.0                        0.0   
16                          0.0                        1.0   
17                          1.0                        0.0   
18                          0.0                        0.0   
19                          0.0                        0.0   

    ordinalencoder__Size  remainder__Sales  
0                    2.0            100000  
1                    1.0            222000  
2                    0.0            150000  
3                    1.0            180000  
4                    2.0            120000  
5                    0.0            200000  
6                    1.0            250000  
7                    2.0            175000  
8                    1.0            140000  
9                    2.0            230000  
10                   0.0            260000  
11                   1.0            190000  
12                   0.0            160000  
13                   1.0            210000  
14                   2.0            240000  
15                   0.0            170000  
16                   1.0            130000  
17                   0.0            220000  
18                   1.0            200000  
19                   2.0            180000

In [160]:
#now for the drop :

In [161]:
ct2=make_column_transformer(
    (ohe, ['City']),
    (ode, ['Size']),
    remainder='drop'
)

In [162]:
ct2.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['City']),
                                ('ordinalencoder', OrdinalEncoder(), ['Size'])])

In [165]:
df_dropped=ct2.fit_transform(df)

In [166]:
df_dropped

onehotencoder__City_Jacksonville  onehotencoder__City_Miami  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        1.0   
3                                1.0                        0.0   
4                                0.0                        0.0   
5                                0.0                        0.0   
6                                0.0                        1.0   
7                                1.0                        0.0   
8                                0.0                        0.0   
9                                0.0                        0.0   
10                               0.0                        1.0   
11                               1.0                        0.0   
12                               0.0                        0.0   
13                               0.0                        0.0   
14                               0.0                        1.0   
15                               1.0                        0.0   
16                               0.0                        0.0   
17                               0.0                        0.0   
18                               0.0                        1.0   
19                               1.0                        0.0   

    onehotencoder__City_Orlando  onehotencoder__City_Tampa  \
0                           0.0                        1.0   
1                           1.0                        0.0   
2                           0.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        1.0   
5                           1.0                        0.0   
6                           0.0                        0.0   
7                           0.0                        0.0   
8                           0.0                        1.0   
9                           1.0                        0.0   
10                          0.0                        0.0   
11                          0.0                        0.0   
12                          0.0                        1.0   
13                          1.0                        0.0   
14                          0.0                        0.0   
15                          0.0                        0.0   
16                          0.0                        1.0   
17                          1.0                        0.0   
18                          0.0                        0.0   
19                          0.0                        0.0   

    ordinalencoder__Size  
0                    2.0  
1                    1.0  
2                    0.0  
3                    1.0  
4                    2.0  
5                    0.0  
6                    1.0  
7                    2.0  
8                    1.0  
9                    2.0  
10                   0.0  
11                   1.0  
12                   0.0  
13                   1.0  
14                   2.0  
15                   0.0  
16                   1.0  
17                   0.0  
18                   1.0  
19                   2.0